export const USER_REQUEST = 'USER_REQUEST'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_FAILED = 'REQUEST_FAILED'
export const CONNECTION_REQUEST_SUCCESS = 'CONNECTION_REQUEST_SUCCESS'
